server:
  port: 7051

spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ratingService

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-5202901.okta.com/oauth2/default

  config:
    import: optional:configserver:http://localhost:7054
    
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

      